### ISSUE TITLE
Handle None in _is_classified_as_cause

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/mozci#133] opened 2020-04-02 11:04 UTC
`push.id==109919` is broken:

```
ERROR: 'NoneType' object is not subscriptable
	File "C:\Users\kyle\code-ss\mo-etl\.venv\lib\site-packages\mozci\push.py", line 469, in _is_classified_as_cause
```

Full trace

``
WARNING: could not get regressions for 109919
	File "C:\Users\kyle\code-ss\mo-etl\mo_etl\schedulers.py", line 117, in process_one
	File "C:\Users\kyle\code-ss\mo-etl\mo_etl\schedulers.py", line 169, in process
	File "C:\Users\kyle\code-ss\mo-etl\mo_etl\schedulers.py", line 216, in main
	File "C:\Users\kyle\code-ss\mo-etl\mo_etl\schedulers.py", line 234, in <module>
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\pydevd.py", line 1418, in _exec
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\pydevd.py", line 1411, in run
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\pydevd.py", line 2060, in main
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\pydevd.py", line 2066, in <module>
caused by
	ERROR: 'NoneType' object is not subscriptable
	File "C:\Users\kyle\code-ss\mo-etl\.venv\lib\site-packages\mozci\push.py", line 469, in _is_classified_as_cause
	File "C:\Users\kyle\code-ss\mo-etl\.venv\lib\site-packages\mozci\push.py", line 511, in get_candidate_regressions
	File "C:\Users\kyle\code-ss\mo-etl\.venv\lib\site-packages\mozci\push.py", line 552, in bustage_fixed_by
	File "C:\Users\kyle\code-ss\mo-etl\.venv\lib\site-packages\adr\util\memoize.py", line 45, in __get__
	File "C:\Users\kyle\code-ss\mo-etl\.venv\lib\site-packages\mozci\push.py", line 580, in get_regressions
	File "C:\Users\kyle\code-ss\mo-etl\mo_etl\schedulers.py", line 114, in process_one
	File "C:\Users\kyle\code-ss\mo-etl\vendor\mo_logs\__init__.py", line 305, in warning
	File "C:\Users\kyle\code-ss\mo-etl\mo_etl\schedulers.py", line 117, in process_one
	File "C:\Users\kyle\code-ss\mo-etl\mo_etl\schedulers.py", line 169, in process
	File "C:\Users\kyle\code-ss\mo-etl\mo_etl\schedulers.py", line 216, in main
	File "C:\Users\kyle\code-ss\mo-etl\mo_etl\schedulers.py", line 234, in <module>
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\pydevd.py", line 1418, in _exec
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\pydevd.py", line 1411, in run
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\pydevd.py", line 2060, in main
	File "C:\Users\kyle\.IntelliJIdea2019.2\config\plugins\python\helpers\pydev\pydevd.py", line 2066, in <module>
```

**Comment by marco-c** [comment] 2020-04-02 11:19
The full trace seems to be missing some info, but this is likely a duplicate of #131.

**Comment by marco-c** [comment] 2020-04-02 11:19
Yes, it's the same line.

**Closed by marco-c** 2020-04-02 11:19 UTC
Labels: smart-sched
