### ISSUE TITLE
Handle case where shadow-schedulers didn't run gracefully

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#82] opened 2020-03-11 17:27 UTC
Pushes with DONTBUILD in the commit message won't run the shadow-schedulers. There may be other cases they don't run too.

Kyle hit a push like this and tried to call `Push.get_shadow_scheduler_tasks()` and it blew up:
```
Traceback (most recent call last):
  File "c:\users\kyle\code\ci-recipes\.venv\lib\site-packages\mozci\util\taskcluster.py", line 86, in find_task_id
    response = _do_request(get_index_url(index_path))
  File "c:\users\kyle\code\ci-recipes\.venv\lib\site-packages\mozci\util\taskcluster.py", line 27, in _do_request
    response.raise_for_status()
  File "c:\users\kyle\code\ci-recipes\.venv\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.autoland.revision.5906a8051c5446717e76f9010aee37e9f85eae83.source.shadow-scheduler-relevant_tests
​
During handling of the above exception, another exception occurred:
​
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kyle\code\ci-recipes\.venv\Scripts\adr.exe\__main__.py", line 9, in <module>
  File "c:\users\kyle\code\ci-recipes\.venv\lib\site-packages\adr\cli.py", line 237, in main
    result = handler(remainder)
  File "c:\users\kyle\code\ci-recipes\.venv\lib\site-packages\adr\cli.py", line 194, in handle_recipe
    data = run_recipe(config.recipe, remainder)
  File "c:\users\kyle\code\ci-recipes\.venv\lib\site-packages\adr\recipe.py", line 91, in run_recipe
    output = mod.run(Namespace(**parsed_args))
  File "C:\Users\kyle\code\ci-recipes\recipes\scheduler_analysis.py", line 244, in run
    scores[s.name].update(s.analyze(push))
  File "C:\Users\kyle\code\ci-recipes\recipes\scheduler_analysis.py", line 154, in analyze
    tasks = self.get_tasks(push)
  File "C:\Users\kyle\code\ci-recipes\recipes\scheduler_analysis.py", line 124, in get_tasks
    tasks = push.get_shadow_scheduler_tasks(self.name)
  File "c:\users\kyle\code\ci-recipes\.venv\lib\site-packages\adr\util\memoize.py", line 26, in method_call
    cache[args] = self.func(instance, *args)
  File "c:\users\kyle\code\ci-recipes\.venv\lib\site-packages\mozci\push.py", line 536, in get_shadow_scheduler_tasks
    task = Task(id=find_task_id(index))
  File "c:\users\kyle\code\ci-recipes\.venv\lib\site-packages\mozci\util\taskcluster.py", line 89, in find_task_id
    raise KeyError("index path {} not found".format(index_path))
KeyError: 'index path gecko.v2.autoland.revision.5906a8051c5446717e76f9010aee37e9f85eae83.source.shadow-scheduler-relevant_tests not found'
```

We should raise a proper exception or return None or something when this happens.

**Comment by marco-c** [comment] 2020-07-07 11:49
Closing as duplicate of #144 (I know this one is older, but there's more discussion there).

**Closed by marco-c** 2020-07-07 11:49 UTC
Labels: duplicate
